### ISSUE TITLE
Connecting to RavenDB server using a self-signed certificate

### ISSUE THREAD

**Issue by huyhoangepay** [ravendb/jvm-client#23]
I am experimenting with RavenDB and Java. My RavenDB is installed on a Ubuntu host using a self-signed certificate. Then I generate the client certificate using the management UI. After that I got a zip file, which I extracted and use it in the code like so:
```java
var keystore = CertificateUtils.createKeystore(
        "path\\to\\app.crt",
        "path\\to\\app.key");

try (DocumentStore store = new DocumentStore(new String[]{HTTPS_ENDPOINT}, DATABASE)) {
    store.setCertificate(keystore);

    store.initialize();

    // do your work here
    var session = store.openSession();
    session.load(Object.class, DOCUMENT_ID);
}
```
However I got the following error:
```
22:04:25.925 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {s}-><HTTPS_ENDPOINT>][total available: 0; route allocated: 0 of 30; total allocated: 0 of 40]
Exception in thread "main" net.ravendb.client.exceptions.RavenException: An exception occurred while contacting <HTTPS_ENDPOINT>/databases/<DATABASE>/docs?&id=<DOCUMENT_ID>.
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
The server at <HTTPS_ENDPOINT>/databases/<DATABASE>/docs?&id=<DOCUMENT_ID> responded with status code: 503
	at net.ravendb.client.exceptions.ExceptionDispatcher.get(ExceptionDispatcher.java:37)
	at net.ravendb.client.http.RequestExecutor.readExceptionFromServer(RequestExecutor.java:1579)
	at net.ravendb.client.http.RequestExecutor.handleServerDown(RequestExecutor.java:1253)
	at net.ravendb.client.http.RequestExecutor.sendRequestToServer(RequestExecutor.java:868)
	at net.ravendb.client.http.RequestExecutor.execute(RequestExecutor.java:726)
	at net.ravendb.client.http.RequestExecutor.execute(RequestExecutor.java:681)
	at net.ravendb.client.http.RequestExecutor.unlikelyExecute(RequestExecutor.java:484)
	at net.ravendb.client.http.RequestExecutor.execute(RequestExecutor.java:444)
	at net.ravendb.client.documents.session.DocumentSession.load(DocumentSession.java:340)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:369)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:199)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at net.ravendb.client.http.RavenCommand.send(RavenCommand.java:115)
	at net.ravendb.client.http.RequestExecutor.send(RequestExecutor.java:882)
	at net.ravendb.client.http.RequestExecutor.sendRequestToServer(RequestExecutor.java:861)
	... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 32 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 37 more

```
I believe the `SSLHandshakeException` is caused because the client library failed to verify the server certificate which is self-signed.
Is there an option to skip the certificate verification?

**Comment by huyhoangepay** [comment]
Actually, I figured out a work-around.
For those who have the same problem, you can tell the Document store to trust the server's certificate by loading the server's certificate into a trust store.
```java
KeyStore trustStore = KeyStore.getInstance("PKCS12");
trustStore.load(new FileInputStream("path\\to\\server.pfx"), "password".toCharArray());

store.setTrustStore(trustStore);
```
Still, it would be nice if there's an option to force the client to skip certificate validation.

**Comment by ayende** [comment]
Hi,
You can configure RavenDB to trust the server using the following process:

Register yourself on `RequestExecutor.configureHttpClient` ( 
https://github.com/ravendb/ravendb-jvm-client/blob/v5.0/src/main/java/net/ravendb/client/http/RequestExecutor.java#L61 )

Inside the call, setup `setSSLHostnameVerifier` to apply your own logic to that.
