### ISSUE TITLE
Unable to find class by name in Quarkus CDI context - SOLVED

### ISSUE THREAD

**Issue by davidmoshal** [ravendb/jvm-client#25]
The following works in kotlin:
```kt

fun main(args: Array<String>) {
    val store: IDocumentStore = DocumentStore("http://localhost:8083", "test-db")
    store.initialize()

    store.openSession().apply {
        val d = Doctor()
        d.name = "dave"
        store(d, "1")
        saveChanges()
    }

    store.openSession().apply {
        val d = load(Doctor::class.java, "1")
        println(d.name)
    }

    store.close()
}
```

However, the exact same thing fails if called from a REST endpoint running in Quarkus:
```kt
Path("/doctors")
class DoctorResource {

    @GET
    @Path("/doctor")
    fun getDoctor(): Doctor? {

        val store: IDocumentStore = DocumentStore("http://localhost:8083", "test-db")
        store.initialize()

        store.openSession().apply {
            val d = Doctor()
            d.name = "dave"
            store(d, "1")
            saveChanges()
        }

        var d_from_db:Doctor? = null

        store.openSession().apply {
            d_from_db = load(Doctor::class.java, "1")
        }

        println(d_from_db)

        return d_from_db
    }

```

The error is as follows:

```sh
java.lang.IllegalStateException: Could not convert document 1 to entity of type au21.engine.framework.endpoints.Doctor
	at net.ravendb.client.documents.session.EntityToJson.convertToEntity(EntityToJson.java:178)
	at net.ravendb.client.documents.session.InMemoryDocumentSessionOperations.trackEntity(InMemoryDocumentSessionOperations.java:630)
	at net.ravendb.client.documents.session.InMemoryDocumentSessionOperations.trackEntity(InMemoryDocumentSessionOperations.java:574)
	at net.ravendb.client.documents.session.operations.LoadOperation.getDocument(LoadOperation.java:146)
	at net.ravendb.client.documents.session.operations.LoadOperation.getDocument(LoadOperation.java:132)
	at net.ravendb.client.documents.session.DocumentSession.load(DocumentSession.java:344)
	at au21.engine.framework.endpoints.DoctorResource.getDoctor(DoctorResource.kt:39)
	at au21.engine.framework.endpoints.DoctorResource_Subclass.getDoctor$$superaccessor1(DoctorResource_Subclass.zig:189)
	at au21.engine.framework.endpoints.DoctorResource_Subclass$$function$$4.apply(DoctorResource_Subclass$$function$$4.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at au21.engine.framework.endpoints.DoctorResource_Subclass.getDoctor(DoctorResource_Subclass.zig:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: net.ravendb.client.exceptions.RavenException: Unable to find class by name = au21.engine.framework.endpoints.Doctor
	at net.ravendb.client.documents.conventions.DocumentConventions.lambda$new$4(DocumentConventions.java:168)
	at net.ravendb.client.documents.conventions.DocumentConventions.getJavaClassByName(DocumentConventions.java:645)
	at net.ravendb.client.documents.session.EntityToJson.convertToEntity(EntityToJson.java:157)
	... 49 more
Caused by: java.lang.ClassNotFoundException: au21.engine.framework.endpoints.Doctor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:421)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.ravendb.client.documents.conventions.DocumentConventions.lambda$new$4(DocumentConventions.java:166)
	... 51 more
null
```

**Comment by davidmoshal** [comment]
The solution appears to be as follows (ie: for use in a Quarkus CDI context):

```kt
store.conventions.setFindJavaClassByName { name -> Class.forName(name) }
```

**Comment by ml054** [comment]
@davidmoshal the overload you pasted seems to match original implementation (except error catching) https://github.com/ravendb/ravendb-jvm-client/blob/fe30e0a534c7246699d7f7a3baa285a31d862525/src/main/java/net/ravendb/client/documents/conventions/DocumentConventions.java#L169

Not sure why it starts to work with this change.

**Comment by ayende** [comment]
Different class loader?

**Comment by ml054** [comment]
Hmm might be - java uses by default class loader of caller. Will dig into that.

**Comment by ml054** [comment]
Ok we don't have an access to right class loader in this case so manual action is required. It will open documentation ticket for that.

**Comment by davidmoshal** [comment]
> @davidmoshal the overload you pasted seems to match original implementation (except error catching)
> 
> https://github.com/ravendb/ravendb-jvm-client/blob/fe30e0a534c7246699d7f7a3baa285a31d862525/src/main/java/net/ravendb/client/documents/conventions/DocumentConventions.java#L169
> 
> Not sure why it starts to work with this change.

Yes, correct, it's the same code.
However: this code example is running in the context of Quarkus CDI (version 1.13.7-Final).
Presumably it's something to do with how Quarkus CDI manages classloaders.
see: https://quarkus.io/guides/class-loading-reference

Note: I am running it with Quarkus live-reloading, so that could also be an issue.

Easiest way to test would be to create a simple Quarkus app from here:
- https://code.quarkus.io/

**Comment by ml054** [comment]
![image](https://user-images.githubusercontent.com/1250431/124864044-85669080-dfb8-11eb-9183-514a58680765.png)

It starts to work since we caller has different class loader. 

Like I said it might be hard/impossible to solve that in generic way. However we mention about that in docs.

**Comment by ml054** [comment]
https://issues.hibernatingrhinos.com/issue/RDoc-1961
