### ISSUE TITLE
Error from subscription: `Server returned illegal type message when expecting connection status, was:ERROR`

### ISSUE THREAD

**Issue by vijayakumarsuraj** [ravendb/jvm-client#46]
Seeing this error at pretty regular intervals from my subscription. 
```
java.lang.IllegalStateException: Server returned illegal type message when expecting connection status, was:ERROR
	at net.ravendb.client.documents.subscriptions.SubscriptionWorker.assertConnectionState(SubscriptionWorker.java:337)
	at net.ravendb.client.documents.subscriptions.SubscriptionWorker.processSubscription(SubscriptionWorker.java:416)
	at net.ravendb.client.documents.subscriptions.SubscriptionWorker.lambda$runSubscriptionAsync$4(SubscriptionWorker.java:586)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

After some more digging, I can see the actual error that the server sent back was:
```
Raven.Server.Rachis.RachisApplyException: Can't update subscription with name 'values/kwl-sales-db/subscriptions/LegacyPurchaseMigrator' by node B, because it's not it's task to update this subscription
   at Raven.Server.ServerWide.Commands.Subscriptions.UpdateSubscriptionClientConnectionTime.GetUpdatedValue(Int64 index, RawDatabaseRecord record, JsonOperationContext context, BlittableJsonReaderObject existingValue) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\Commands\Subscriptions\UpdateSubscriptionClientConnectionTime.cs:line 38
   at Raven.Server.ServerWide.Commands.UpdateValueForDatabaseCommand.Execute(ClusterOperationContext context, Table items, Int64 index, RawDatabaseRecord record, RachisState state, Object& result) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\Commands\UpdateValueForDatabaseCommand.cs:line 54
   at Raven.Server.ServerWide.ClusterStateMachine.SetValueForTypedDatabaseCommand(ClusterOperationContext context, String type, BlittableJsonReaderObject cmd, Int64 index, Leader leader, Object& result) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 1397
   at Raven.Server.ServerWide.ClusterStateMachine.Apply(ClusterOperationContext context, BlittableJsonReaderObject cmd, Int64 index, Leader leader, ServerStore serverStore) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 707
--- End of stack trace from previous location ---
   at Raven.Server.Rachis.Leader.PutAsync(CommandBase command, TimeSpan timeout) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\Rachis\Leader.cs:line 691
   at Raven.Server.ServerWide.ServerStore.SendToLeaderAsyncInternal(TransactionOperationContext context, CommandBase cmd) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\ServerStore.cs:line 2930
   at Raven.Server.ServerWide.ServerStore.SendToLeaderAsyncInternal(CommandBase cmd) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\ServerStore.cs:line 2915
   at Raven.Server.ServerWide.ServerStore.SendToLeaderAsync(CommandBase cmd) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\ServerWide\ServerStore.cs:line 2749
   at Raven.Server.Documents.Subscriptions.SubscriptionStorage.UpdateClientConnectionTime(Int64 id, String name, String mentorNode) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\Documents\Subscriptions\SubscriptionStorage.cs:line 176
   at Raven.Server.Documents.TcpHandlers.SubscriptionConnection.NotifyClientAboutSuccess(Int64 registerConnectionDurationInTicks) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\Documents\TcpHandlers\SubscriptionConnection.cs:line 238
   at Raven.Server.Documents.TcpHandlers.SubscriptionConnection.Run(TcpConnectionOptions tcpConnectionOptions, IDisposable subscriptionConnectionInProgress) in C:\Builds\RavenDB-Stable-5.3\53004\src\Raven.Server\Documents\TcpHandlers\SubscriptionConnection.cs:line 402
```

The client re-connects and the subscription continues. But it does appear like this shouldn't be happening as part of normal operation?

I am on v5.2.2 of the client. This error was coming from our production cluster that has 3 nodes.

**Comment by ayende** [comment]
That is an indication that the subscription's ownership was moved. In that case, the batch will be retried transparently.
That isn't something that you should be seeing directly, it is handled internally.

**Comment by vijayakumarsuraj** [comment]
This error was showing up every 5-10 seconds. Would it be normal for the subscription ownership to change that often?

**Comment by ayende** [comment]
Having that happen on a rare basis is fine and expected. 
Having that happen all the time in not normal. Do you see a lot of elections on your cluster? Is the owner node on the subscription changes? 
Who _is_ the owner node?

**Comment by vijayakumarsuraj** [comment]
So, the subscription was working through a _backlog_ of about 40M documents. Now that it has caught up (only a few updates per second now), these errors seem to have gone away. 

If you don't think this is something the SDK should be handling more transparently, I'm happy to close this issue.
